# Generated by Django 4.0.4 on 2022-05-06 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_description', models.TextField()),
                ('item_price', models.FloatField()),
                ('item_cost', models.FloatField()),
                ('item_pic', models.CharField(max_length=60)),
                ('is_virtual', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=10, unique=True)),
                ('sku_code', models.CharField(max_length=20, unique=True)),
                ('sku_price', models.FloatField()),
                ('size_code', models.CharField(choices=[('XS', 'Extra small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra extra Large')], max_length=3)),
                ('color_code', models.CharField(max_length=3)),
                ('color_code_desc', models.CharField(max_length=100)),
                ('backordereable', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
