# Generated by Django 4.0.4 on 2022-07-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_i_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinate',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
